### ISSUE TITLE
Not found ./bootstrap.sh

### ISSUE THREAD

**Issue by xiva-wgt** [mwaeckerlin/mingw#1]
Hello!
bootstrap.sh the file you want to create? In source code build.sh it takes parameters so I think this file should be in the image, not created by itself.

`docker run -it --rm -v C:/build:/workdir mwaeckerlin/mingw /build.sh -g https://github.com/twogood/unshield.git
Unable to find image 'mwaeckerlin/mingw:latest' locally
latest: Pulling from mwaeckerlin/mingw
d3938036b19c: Pull complete
a9b30c108bda: Pull complete
67de21feec18: Pull complete
817da545be2b: Pull complete
d967c497ce23: Pull complete
16857b8f23a0: Pull complete
8e1531c23e2a: Pull complete
b0db0011a608: Pull complete
cb64da20d485: Pull complete
da846f05f70d: Pull complete
e63fab3c3fcd: Pull complete
edff0f980e60: Pull complete
0b730a4364a7: Pull complete
5ef2a139c47a: Pull complete
e7a57916822d: Pull complete
335f1dfe7b1d: Pull complete
e573729d338c: Pull complete
b61e5f548180: Pull complete
699c7abd15b6: Pull complete
d963c701b8b4: Pull complete
9dad2c8bce82: Pull complete
d8312b41ea4e: Pull complete
111fb6f04381: Pull complete
324483b5520d: Pull complete
7c0e55a271d4: Pull complete
3eb9005d0053: Pull complete
Digest: sha256:cb009d90f8bc0c360454215d8a240733960cf4132420ae0ce7295a2f5a3ecf89
Status: Downloaded newer image for mwaeckerlin/mingw:latest
+ cd /workdir
+ test -n https://github.com/twogood/unshield.git
+ git clone https://github.com/twogood/unshield.git unshield.git
Cloning into 'unshield.git'...
remote: Counting objects: 1098, done.
remote: Total 1098 (delta 0), reused 0 (delta 0), pack-reused 1098
Receiving objects: 100% (1098/1098), 226.22 KiB | 368.00 KiB/s, done.
Resolving deltas: 100% (650/650), done.
Checking connectivity... done.
+ test -n ''
+ test -n unshield.git
+ cd unshield.git
+ ./bootstrap.sh -c --host=x86_64-w64-mingw32 --prefix=/workdir/usr --bindir=/workdir/usr/exe --sbindir=/workdir/usr/exe --libdir=/workdir/usr/exe --libexecdir=/workdir/usr/exe CPPFLAGS=-I/workdir/usr/include LDFLAGS=-L/workdir/usr/exe PKG_CONFIG_PATH=/workdir/usr/exe/pkgconfig
/build.sh: line 97: ./bootstrap.sh: No such file or directory`

**Comment by mwaeckerlin** [comment]
Sorry for the delay in the answer, I did not notice your question.

`bootstrap.sh` is related to my [bootstrap-build-environment](https://mrw.sh/development/bootstrap-build-environment).

I'll extend the script so that it falls back to `./configure` if `./bootstrap.sh` does not exist.

**Comment by mwaeckerlin** [comment]
In your case, [the project](https://github.com/twogood/unshield.git) is not based on the [GNU Build System](https://en.wikipedia.org/wiki/GNU_Build_System) using `./configure && make && make install`, so it is not supported by my image. Especially CMake is a pain in the ass.
